[package]
name = "wz-conf"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Configuration options for wz"

[dependencies.clap]
version = "3.2.20"
default-features = false
features = [
  "std",
  "color",
  "suggestions",
  "derive",
  "wrap_help"
]
