name: Run benchmarks
on: workflow_dispatch
jobs:
  criterion_bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        path:
          - "crates/wz-utf8"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - run: cargo bench
        working-directory: ${{ matrix.path }}
      - uses: actions/upload-artifact@v2
        with:
          name: bench-${{ matrix.path }}
          path: |
            target/criterion
