name: Build release artifacts on release creation
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build for ${{ matrix.target }}
    strategy:
      matrix:
        include:
          # Linux
          - target: "x86_64-unknown-linux-gnu"
            os: ubuntu-latest
          # Windows
          - target: "aarch64-pc-windows-msvc"
            os: windows-latest
          - target: "x86_64-pc-windows-msvc"
            os: windows-latest
          # macOS
          - target: "aarch64-apple-darwin"
            os: macos-latest
          - target: "x86_64-apple-darwin"
            os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      WZ_MISC_FOLDER: "~/temp"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key:
            ${{ matrix.target }}-${{ matrix.os }}-cargo-${{
            hashFiles('**/Cargo.lock') }}

      - name: Set up target ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary for target ${{ matrix.target }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Move artifacts to ${{ env.WZ_MISC_FOLDER }}
        run: |
          mv target/${{ matrix.target }}/release/wz* ${{ env.WZ_MISC_FOLDER }}
        continue-on-error: true

      - run: zip wz-${{ matrix.target }} ${{ env.WZ_MISC_FOLDER }} -r

      - uses: svenstaro/upload-release-action@v2
        with:
          asset_name: wz-${{ matrix.target }}
          file: wz-${{ matrix.target }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
