name: Check changes
on:
  push:
    branches:
      - "**"
      - "*"
  pull_request:
    branches:
      - "master"
jobs:
  make_ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Disable autocrlf
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run:
          rustup update ${{ matrix.toolchain }} && rustup default ${{
          matrix.toolchain }}
      - run: make ci
